In [7]:
from google.colab import files
uploaded = files.upload()

Saving Buyer Ratio.csv to Buyer Ratio.csv


In [8]:
import pandas as pd
import io


In [9]:
import numpy as np
from scipy import stats


In [10]:
df = pd.read_csv(io.BytesIO(uploaded['Buyer Ratio.csv']))
print(df)

  Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750


In [11]:
df_table=df.iloc[:,1:6]
df_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [12]:
df_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [13]:
val=stats.chi2_contingency(df_table)

In [14]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [15]:
type(val)

tuple

In [16]:
no_of_rows=len(df_table.iloc[0:2,0])
no_of_columns=len(df_table.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=', degree_of_f)

Degree of Freedom= 3


In [17]:
Expected_value=val[3]

In [18]:
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [19]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(df_table.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic


1.5152956451130446

In [20]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [21]:
print ('Dependent (reject H0)')
print ('Independent (fail to reject H0)')

Dependent (reject H0)
Independent (fail to reject H0)


In [22]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

0.6787446296467897

In [ ]:
#failed to reject null hypothesis